Website_StorePhone3/Models/DB/brand.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_StorePhone3.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class brand
    {
        public brand()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Tên nhà sản xuất không được trống")]
        [Display(Name = "BrandName")]
        public string name { get; set; }
        [Required(ErrorMessage = "Logo không được trống")]
        [Display(Name = "BrandLogo")]
        public string logo { get; set; }
        public int activeFlag { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}

Website_StorePhone3/Areas/Admin/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Website_StorePhone3.Models.DB;

namespace Website_StorePhone3.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        dotnetstorephoneEntities db = new dotnetstorephoneEntities();
        // GET: Admin/Brand
        public ActionResult Index()
        {
            List<brand> brands = db.brands.ToList();
            return View(brands);
        }
        public ActionResult addBrand()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addBrand([Bind(Include = "id,activeFlag,createDate,updateDate")] brand brands, string name, HttpPostedFileBase logo)
        {
            /*  string fileName = System.IO.Path.GetFileName(logo.FileName);
              string urlImage = Server.MapPath("~/Image/logo/" + fileName);
              logo.SaveAs(urlImage);
              brands.logo = "Image/logo/" + fileName;
              brands.name = name;
              brands.activeFlag = 1;
              brands.createDate = DateTime.Now;
              brands.updateDate = DateTime.Now;
              db.brands.Add(brands);
              db.SaveChanges();
              return RedirectToAction("Index");*/

            /*  string fileName = System.IO.Path.GetFileName(logo.FileName);
              string urlImage = Server.MapPath("~/Image/logo/" + fileName);
              logo.SaveAs(urlImage);
              brands.logo = "Image/logo/" + fileName;
              brands.name = name;
              brands.activeFlag = 1;
              brands.createDate = DateTime.Now;
              brands.updateDate = DateTime.Now;
              db.brands.Add(brands);
              db.SaveChanges();
              return RedirectToAction("Index");*/

            /*if (ModelState.IsValid)
            {


            }
            else
            {
                if(logo !=null && logo.ContentLength>0)
                {
                    string fileName = System.IO.Path.GetFileName(logo.FileName);
                    string urlImage = Server.MapPath("~/Image/logo/" + fileName);
                    logo.SaveAs(urlImage);
                    brands.logo = "Image/logo/" + fileName;
                    brands.name = name;
                    brands.activeFlag = 1;
                    brands.createDate = DateTime.Now;
                    brands.updateDate = DateTime.Now;
                    db.brands.Add(brands);
                    db.SaveChanges();
                    return RedirectToAction("Index");*/
           
           
            if (logo != null && logo.ContentLength > 0)
            {
                string fileName = System.IO.Path.GetFileName(logo.FileName);
                string urlImage = Server.MapPath("~/Image/logo/" + fileName);
                logo.SaveAs(urlImage);
                brands.logo = "Image/logo/" + fileName;
                brands.name = name;
                brands.activeFlag = 1;
                brands.createDate = DateTime.Now;
                brands.updateDate = DateTime.Now;
                db.brands.Add(brands);
                db.SaveChanges();
                return RedirectToAction("Index");


            
            }

            if (ModelState.IsValid)
            {
              

            }
            return View(brands);

        }

        internal bool checkName(string name)
        {
            var temp = db.brands.Where(m => m.name.Equals(name)).ToList();
            if(temp.Count == 0)
                return true;
            return false;      
        }
        // GET :Brand/Delete /
        public ActionResult Delete(int id)
        {
            brand modifybrand = db.brands.Find(id);
            if (modifybrand == null)
            {
                return HttpNotFound();
            }
            modifybrand.activeFlag = 0;
            db.Entry(modifybrand).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");

        }


        // GET:Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            brand brand = db.brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }
        // POST: Brand/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,activeFlag,createDate,updateDate")] brand brand, string editname, HttpPostedFileBase editlogo)
        {
            if (ModelState.IsValid)
            {
                brand modifybrand = db.brands.Find(brand.id);
                if (modifybrand != null)
                {
                    if (editlogo != null && editlogo.ContentLength > 0)
                    {

                        string fileName = System.IO.Path.GetFileName(editlogo.FileName);
                        string urlImage = Server.MapPath("~/Image/" + fileName);
                        editlogo.SaveAs(urlImage);
                        modifybrand.name = editname;
                        modifybrand.updateDate = DateTime.Now;
                        modifybrand.logo = "Image/" + fileName;
                        modifybrand.updateDate = DateTime.Now;
                    }
                    else
                    {
                        modifybrand.name = editname;
                        modifybrand.updateDate = DateTime.Now;

                    }
                }
                db.Entry(modifybrand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

    }
}

Website_StorePhone3/Areas/Admin/Views/Brand/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

@model Website_StorePhone3.Models.DB.brand
<ul class="nav nav-list">
    <li class="">
        <a href="index.html">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> Trang Chủ </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">
                Cấu hình Users
            </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                @*  <a href="manage_user.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Quản lí User
                    </a>*@
                @Html.ActionLink("Quản lý User", "manager_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="typography.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Danh sách quyền
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="profile_users.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách User
                    </a>*@
                @Html.ActionLink("Danh sách User", "profile_users", "HomeAdmin")
                <b class="arrow"></b>
            </li>
            <li class="">
                @* <a href="add_users.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm User
                    </a>*@
                @Html.ActionLink("Thêm User", "add_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>




        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Quản Lý Danh Mục </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                @* <a href="manage_user.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Loại danh mục
                    </a>*@
                @Html.ActionLink("Loại danh mục", "manager_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thêm danh mục", "addCategory", "Category")
                <b class="arrow"></b>
            </li>

        </ul>
    </li>

    <li class="active open">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text">Quản lý nhà sản xuất</span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">

            <li class="active">
                @*   <a href="profile_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thông tin nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thông tin nhà sản xuất", "Index", "Brand")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thêm nhà sản xuất", "addBrand", "Brand")
                <b class="arrow"></b>
            </li>

        </ul>


    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text">Quản lý sản phẩm </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                @*  <a href="profile_product.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách sản phẩm
                    </a>*@
                @Html.ActionLink("Danh sách sản phẩm", "profile_product", "HomeAdmin")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_product.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm sản phẩm
                    </a>*@
                @Html.ActionLink("Thêm sản phẩm", "add_Product", "HomeAdmin")
                <b class="arrow"></b>
            </li>
            <li class="">
                @*<a href="manage_color.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách màu sắc
                    </a>*@
                @Html.ActionLink("Danh sách màu sắc", "manager_color", "HomeAdmin")
                <b class="arrow"></b>
            </li>

        </ul>


    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-calendar"></i>
            <span class="menu-text">Quản lý đơn hàng </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                @*  <a href="manage_order.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách đơn hàng
                    </a>*@
                @Html.ActionLink("Danh sách đơn hàng", "manager_order", "HomeAdmin")
                <b class="arrow"></b>
            </li>


        </ul>


    </li>




</ul><!-- /.nav-list -->


<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
    <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
</div>
        </div>
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="index.html">Trang chủ</a>
                </li>

                <li>
                    <a href="index.html">Quản lý nhà sản xuất</a>
                </li>
                <li class="active">Sửa nhà sản xuất</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">


            <div class="page-header">
                <h1>
                    Quản lý nhà sản xuất
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Sửa nhà sản xuất
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    @using (Html.BeginForm("Edit",
                            "Brand",
                            FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()


                        <!-- PAGE CONTENT BEGINS -->
                        <form class="form-horizontal" role="form">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="name">Tên nhà sản xuất: </label>

                                <div class="col-sm-9">
                                    @* @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "col-xs-10" } })*@
                                    <input type="text" value="@Model.name" id="editname" name="editname" placeholder="Vui lòng nhập tên nhà sản xuất" class="col-xs-10" />
                                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                                </div>
                                <div class="space-4"></div>
                            </div>
                            <div class="hr hr-24"></div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="logo">Logo: </label>

                                <div class="col-sm-9">
                                    <input type="file" name="editlogo" id="editlogo" class="col-xs-10" />
                                </div>
                            </div>
                            <div class="space-4"></div>


                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        Submit
                                    </button>

                                    &nbsp; &nbsp; &nbsp;
                                    <button class="btn" type="reset">
                                        <i class="ace-icon fa fa-undo bigger-110"></i>
                                        Reset
                                    </button>
                                </div>
                            </div>

                            <div class="hr hr-24"></div>

                            <div class="space-24"></div>


                        </form>
                    }
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->

Website_StorePhone3/Areas/Admin/Views/Brand/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
@model IEnumerable<Website_StorePhone3.Models.DB.brand>
<ul class="nav nav-list">
    <li class="">
        <a href="index.html">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> Trang Chủ </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">
                Cấu hình Users
            </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                @*  <a href="manage_user.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Quản lí User
                    </a>*@
                @Html.ActionLink("Quản lý User", "manager_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="typography.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Danh sách quyền
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="profile_users.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách User
                    </a>*@
                @Html.ActionLink("Danh sách User", "profile_users", "HomeAdmin")
                <b class="arrow"></b>
            </li>
            <li class="">
                @* <a href="add_users.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm User
                    </a>*@
                @Html.ActionLink("Thêm User", "add_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>




        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Quản Lý Danh Mục </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                @* <a href="manage_user.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Loại danh mục
                    </a>*@
                @Html.ActionLink("Loại danh mục", "Index", "Category")
                <b class="arrow"></b>
            </li>
            <li class="">
                @* <a href="add_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thêm danh mục", "addCategory", "Category")
                <b class="arrow"></b>
            </li>



        </ul>
    </li>

    <li class="active open">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text">Quản lý nhà sản xuất</span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">

            <li class="active">
                @*   <a href="profile_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thông tin nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thông tin nhà sản xuất", "Index", "Brand")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thêm nhà sản xuất", "addBrand", "Brand")
                <b class="arrow"></b>
            </li>

        </ul>


    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text">Quản lý sản phẩm </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                @*  <a href="profile_product.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách sản phẩm
                    </a>*@
                @Html.ActionLink("Danh sách sản phẩm", "Index", "Product")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_product.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm sản phẩm
                    </a>*@
                @Html.ActionLink("Thêm sản phẩm", "Add", "Product")
                <b class="arrow"></b>
            </li>
            <li class="">
                @*<a href="manage_color.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách màu sắc
                    </a>*@
                @Html.ActionLink("Danh sách màu sắc", "manager_color", "HomeAdmin")
                <b class="arrow"></b>
            </li>

        </ul>


    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-calendar"></i>
            <span class="menu-text">Quản lý đơn hàng </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                @*  <a href="manage_order.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách đơn hàng
                    </a>*@
                @Html.ActionLink("Danh sách đơn hàng", "manager_order", "HomeAdmin")
                <b class="arrow"></b>
            </li>


        </ul>


    </li>




</ul><!-- /.nav-list -->


<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
    <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
</div>
        </div>
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="index.html">Trang chủ</a>
                </li>

                <li>
                    <a href="index.html">Quản lý nhà sản xuất</a>
                </li>
                <li class="active">Thông tin nhà sản xuất</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">


            <div class="page-header">
                <h1>
                    Nhà sản xuất
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Thông tin các nhà sản xuất
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="row">
                        <div class="col-xs-12">

                            <!-- div.table-responsive -->
                            <!-- div.dataTables_borderWrap -->
                            <div>
                                <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th class="center">
                                                <label class="pos-rel">
                                                    <input type="checkbox" class="ace" />
                                                    <span class="lbl"></span>
                                                </label>
                                            </th>
                                            <th>Id</th>
                                            <th>Logo</th>
                                            <th>Tên nhà sản xuất</th>

                                            <th>
                                                <i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>
                                                Hiện thị
                                            </th>


                                            <th>Tác vụ</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            @Html.AntiForgeryToken()
                                            if (item.activeFlag == 1)
                                            {




                                                <!--                                        Dòng thứ nhất-->
                                                <tr>
                                                    <td class="center">
                                                        <label class="pos-rel">
                                                            <input type="checkbox" class="ace" />
                                                            <span class="lbl"></span>
                                                        </label>
                                                    </td>


                                                    <td>@item.id</td>
                                                    <td><img style="max-height:60px" src="~/@item.logo" alt="@item.name" /></td>
                                                    <td class="hidden-480">@item.name</td>
                                                    <!--                                            <td>Thành viên</td>-->

                                                    <td class="hidden-480">
                                                        <div class="col-xs-3">
                                                            <label>
                                                                <input name="switch-field-1" class="ace ace-switch" type="checkbox" />
                                                                <span class="lbl"></span>
                                                            </label>
                                                        </div>
                                                    </td>

                                                    <td>
                                                        <div class="hidden-sm hidden-xs action-buttons">

                                                            <a class="green" href="@Url.Action("Edit/"+item.id)">
                                                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                            </a>
                                                            @*  @Html.ActionLink("Edit", "Edit", new { id = item.id })*@

                                                            <a class="red" href="@Url.Action("Delete/"+item.id)" onclick="return confirm('Bạn chắc chắn xóa? '+'@item.name');">
                                                                <i class="ace-icon fa fa-trash-o bigger-130"></i>

                                                            </a>
                                                            @*@Html.ActionLink("Delete", "Delete", new { id = item.id})*@

                                                        </div>


                                                    </td>
                                                </tr>


                                            }
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <!-- PAGE CONTENT ENDS -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->
<!-- inline scripts related to this page -->
<script type="text/javascript">
    $(document).ready(function () {
        $('#dynamic-table').DataTable();
    });

</script>