Website_StorePhone3/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Website_StorePhone3.Controllers;

namespace Website_StorePhone3.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class HomeAdminController : Controller
    {
        // GET: Admin/HomeAdmin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult add_Product()
        {
            return View();
        }
        public ActionResult add_supplier()
        {
            return View();
        }
        public ActionResult add_user()
        {
            return View();
        }
        public ActionResult edit_supplier()
        {
            return View();
        }
        public ActionResult info_order()
        {
            return View();
        }
        public ActionResult manager_color()
        {
            return View();
        }
        public ActionResult manager_order()
        {
            return View();
        }
        public ActionResult manager_user()
        {
            return View();
        }
        public ActionResult profile_product()
        {
            return View();
        }
        public ActionResult profile_supplier()
        {
            return View();
        }
        public ActionResult profile_users()
        {
            return View();
        }

        //logout
        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            /*  Session.Clear();*/

            return Redirect("/Home/Index");
        }
    }
}

Website_StorePhone3/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<ul class="nav nav-list">
    <li class="active">
        <a href="@Url.Action("Index","Home")">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> Trang Chủ </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">
                Cấu hình Users
            </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                @*  <a href="manage_user.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Quản lí User
                    </a>*@
                @Html.ActionLink("Quản lý User", "manager_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="typography.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Danh sách quyền
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="profile_users.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách User
                    </a>*@
                @Html.ActionLink("Danh sách User", "profile_users", "HomeAdmin")
                <b class="arrow"></b>
            </li>
            <li class="">
                @* <a href="add_users.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm User
                    </a>*@
                @Html.ActionLink("Thêm User", "add_user", "HomeAdmin")
                <b class="arrow"></b>
            </li>




        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Quản Lý Danh Mục </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                @* <a href="manage_user.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Loại danh mục
                    </a>*@
                @Html.ActionLink("Loại danh mục", "Index", "Category")
                <b class="arrow"></b>
            </li>
            <li class="">
                @* <a href="add_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thêm danh mục", "addCategory", "Category")
                <b class="arrow"></b>
            </li>



        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text">Quản lý nhà sản xuất</span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">

            <li class="">
                @*   <a href="profile_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thông tin nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thông tin nhà sản xuất", "Index", "Brand")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_supplier.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm nhà sản xuất
                    </a>*@
                @Html.ActionLink("Thêm nhà sản xuất", "addBrand", "Brand")
                <b class="arrow"></b>
            </li>

        </ul>


    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text">Quản lý sản phẩm </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                @*  <a href="profile_product.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách sản phẩm
                    </a>*@
                @Html.ActionLink("Danh sách sản phẩm", "Index", "Product")
                <b class="arrow"></b>
            </li>

            <li class="">
                @* <a href="add_product.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Thêm sản phẩm
                    </a>*@
                @Html.ActionLink("Thêm sản phẩm", "Add", "Product")
                <b class="arrow"></b>
            </li>
            <li class="">
                @*<a href="manage_color.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách màu sắc
                    </a>*@
                @Html.ActionLink("Danh sách màu sắc", "manager_color", "HomeAdmin")
                <b class="arrow"></b>
            </li>

        </ul>


    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-calendar"></i>
            <span class="menu-text">Quản lý đơn hàng </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>


        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                @*  <a href="manage_order.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Danh sách đơn hàng
                    </a>*@
                @Html.ActionLink("Danh sách đơn hàng", "manager_order", "HomeAdmin")
                <b class="arrow"></b>
            </li>


        </ul>


    </li>




</ul><!-- /.nav-list -->


<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
    <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
</div>
        </div>
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="index.html">Trang chủ</a>
                </li>

                @* <li>
                        <a href="index.html">Quản lý danh mục</a>
                    </li>
                    <li class="active">Thông tin danh mục</li>*@
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">


            <!--<div class="page-header">
                <h1>
                    Danh mục
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Thông tin các danh mục
                    </small>
                </h1>
            </div>-->
            <!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="row">
                        <div class="col-xs-12">

                            <!-- div.table-responsive -->
                            <!-- div.dataTables_borderWrap -->
                            <div>
                                <h1 style="text-align:center">Chào Mừng Bạn Đến Với Trang Chủ Admin</h1>
                            </div>
                        </div>
                    </div>

                    <!-- PAGE CONTENT ENDS -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->
<!-- inline scripts related to this page -->

Website_StorePhone3/Areas/Admin/Views/HomeAdmin/add_Product.cshtml
@{
    ViewBag.Title = "add_Product";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Trang chủ</a>
                </li>

                <li>
                    <a href="#">Danh sách sản phẩm</a>
                </li>
                <li class="active">Thêm sản phẩm</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">


            <div class="page-header">
                <h1>
                    Quản lý sản phẩm
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Thêm sản phẩm
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Mã sản phẩm: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-0" placeholder="Vui lòng nhập mã sản phẩm" class="col-xs-10" />
                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Tên sản phẩm: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" placeholder="Vui lòng nhập tên sản phẩm" class="col-xs-10" />
                            </div>
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Nhà sản xuất :</label>

                            <div class="col-sm-9">
                                <select name="cars" id="carsw">
                                    <option value="volvo">SamSung</option>
                                    <option value="saa2b">Apple</option>
                                    <option value="mercedes">Xiaomi</option>
                                </select>
                            </div>
                        </div>
                        <div class="space-4"></div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Danh mục :</label>

                            <div class="col-sm-9">
                                <select name="cars" id="carsw2">
                                    <option value="volvo">Điện thoại</option>
                                    <option value="saa2b">Laptop</option>
                                    <option value="mercedes">Phụ kiện</option>
                                </select>

                            </div>

                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Màu  sắc:</label>

                            <div class="col-sm-9">
                                <select name="cars" id="carsw2s">
                                    <option value="">Chưa chọn màu sắc</option>
                                    <option value="volvo">Màu đỏ</option>
                                    <option value="saa2b">Màu vàng</option>
                                    <option value="mercedes">Màu tím</option>
                                </select>

                            </div>

                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Số lượng:</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-sad1" placeholder="Vui lòng nhập số lượng" class="col-xs-10" />

                            </div>

                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Ảnh đại diện</label>

                            <div class="col-sm-9">
                                <input type="file" id="form-field-3" placeholder="Vui lòng nhập mật khẩu" class="col-xs-10" />

                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Danh sách ảnh:</label>

                            <div class="col-sm-9">
                                <input type="file" id="form-field-" placeholder="Vui lòng nhập lại mật khẩu" class="col-xs-10" />

                            </div>
                        </div>

                        <div class="space-4"></div>


                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Mô tả tóm tắt:</label>

                            <div class="col-sm-9">
                                <textarea class="col-xs-10"></textarea>
                                <!--                                    <input type="texta" id="form-field-10" placeholder="Vui lòng nhập số điện thoại" class="col-xs-10" />-->

                            </div>
                        </div>






                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Mô tả chi tiết:</label>

                            <div class="col-sm-9">
                                <textarea class="col-xs-10"></textarea>
                                <!--                                    <input type="texta" id="form-field-10" placeholder="Vui lòng nhập số điện thoại" class="col-xs-10" />-->

                            </div>
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Giá sản phẩm:</label>

                            <div class="col-sm-9">
                                <input type="number" id="form-fiel" placeholder="" class="col-xs-10" />

                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Giảm giá:</label>

                            <div class="col-sm-9">
                                <input type="number" id="form-sd" placeholder="" class="col-xs-10" />

                            </div>
                        </div>




                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="button">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Gửi
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="ace-icon fa fa-undo bigger-110"></i>
                                    Làm lại
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>



                        <div class="space-24"></div>


                    </form>


                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->

Website_StorePhone3/Areas/Admin/Views/HomeAdmin/add_supplier.cshtml
@{
    ViewBag.Title = "add_supplier";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="index.html">Trang chủ</a>
                </li>

                <li>
                    <a href="index.html">Quản lý nhà sản xuất</a>
                </li>
                <li class="active">Thêm nhà sản xuất</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">


            <div class="page-header">
                <h1>
                    Quản lý nhà sản xuất
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Thêm nhà sản xuất
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Tên nhà sản xuất: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" placeholder="Vui lòng nhập tên nhà sản xuất" class="col-xs-10" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Logo: </label>

                            <div class="col-sm-9">
                                <input type="file" name="upload" id="form-field-2" class="col-xs-10" />
                            </div>
                        </div>
                        <div class="space-4"></div>


                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="button">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Submit
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="ace-icon fa fa-undo bigger-110"></i>
                                    Reset
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>

                        <div class="space-24"></div>


                    </form>


                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->

Website_StorePhone3/Areas/Admin/Views/HomeAdmin/add_user.cshtml
@{
    ViewBag.Title = "add_user";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Trang chủ</a>
                </li>

                <li>
                    <a href="#">Cấu hình Users</a>
                </li>
                <li class="active">Thêm Users</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">


            <div class="page-header">
                <h1>
                    Cấu hình Users
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Thêm Users
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Tên đăng nhập: </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" placeholder="Vui lòng nhập tên đăng nhập" class="col-xs-10" />
                            </div>
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1">Tên của bạn :</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1-1" placeholder="Vui lòng nhập của bạn" class="col-xs-10" />
                            </div>
                        </div>
                        <div class="space-4"></div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Nhập Email :</label>

                            <div class="col-sm-9">
                                <input type="email" id="form-field-2" placeholder="Vui lòng nhập email" class="col-xs-10" />

                            </div>

                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Nhập Mật khẩu :</label>

                            <div class="col-sm-9">
                                <input type="password" id="form-field-3" placeholder="Vui lòng nhập mật khẩu" class="col-xs-10" />

                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Nhập lại mật khẩu :</label>

                            <div class="col-sm-9">
                                <input type="password" id="form-field-" placeholder="Vui lòng nhập lại mật khẩu" class="col-xs-10" />

                            </div>
                        </div>

                        <div class="space-4"></div>


                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Nhập số điện thoại :</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-10" placeholder="Vui lòng nhập số điện thoại" class="col-xs-10" />

                            </div>
                        </div>






                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Quyền:</label>

                            <div class="col-sm-9">
                                <!--											<input list="html" />-->
                                <!--											<datalist id="html">-->
                                <!--												<option value="Admin"></option>-->
                                <!--												<option value="Nhân viên"></option>-->
                                <!--												<option value="Ví dụ HTML"></option>-->
                                <!--												<option value="Thực hành HTML"></option>-->
                                <!--											</datalist>-->
                                <select name="cars" id="cars">
                                    <option value="volvo">Thành viên</option>
                                    <option value="saab">Nhân viên</option>
                                    <option value="mercedes">Admin</option>
                                </select>

                            </div>
                        </div>




                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="button">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Submit
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="ace-icon fa fa-undo bigger-110"></i>
                                    Reset
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>



                        <div class="space-24"></div>


                    </form>


                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->